### ISSUE TITLE
How to modify the code if it runs in Windows 10

### ISSUE THREAD

**Issue by burnCalories** [CN-UPB/B-JointSP#55]
How to modify the code if it runs in Windows 10

**Comment by stefanbschneider** [comment]
Hi @zhangyangyang0432 , what problems do you have with Windows 10? I think I ran B-JointSP successfully under Windows 10. 

Are you using Python 3.6? That's the version that B-JointSP was tested against. It's possible that versions older than 3.5 and newer than 3.6 do not work.

**Comment by burnCalories** [comment]
main.py: error: the following arguments are required: -n/--network, -t/--template, -s/--sources
I don't know how to enter this command “bjointsp -n parameters/networks/Abilene.graphml -t parameters/templates/fw1chain.yaml -s parameters/sources/source0.yaml”

**Comment by stefanbschneider** [comment]
To use the CLI and pass the arguments, you either need some terminal or pass them through your IDE.

On windows, you could use the Windows Terminal or I often used the [git bash terminal](https://git-scm.com/download/win). Open the terminal and type `bjointsp --help` to see if bjointsp is correctly installed and found.

In an IDE, you can typically configure CLI args in the launch configuration. Eg, for VS Code: https://stackoverflow.com/a/66729306/2745116

Hope, this helps.

**Comment by burnCalories** [comment]
Thank you for your help. The file has been successfully run!
